version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from the protobuf files"
    cmds:
      - protoc -I proto proto/user/user.proto --proto_path=/usr/local/include/google/protobuf --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/bot/bot.proto --proto_path=/usr/local/include/google/protobuf --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
